In [1]:
import torch
from cac import test_accuracy
from hash_model import HASH_Net
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

device = torch.device("cuda")
hash_bits = 64 # 假设哈希编码的位数
model_name = "resnet34"
batch_size = 64
noise_rate=0.0

with open('../labels/64_cifar10_10_class.pkl', 'rb') as f:
    label_hash_codes= torch.load(f)
label_hash_codes.to(device)

# 1. 加载CIFAR-10数据集
transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=False, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size, shuffle=False)


# 确保你的模型架构定义与保存前一致
model = HASH_Net(model_name,hash_bits).to(device)  # YourModelArchitecture是你的模型架构
model.load_state_dict(torch.load(f'./model/nr_{noise_rate}_{model_name}.pth'))  # 加载保存的模型参数
model.eval()  # 设置为评估模式
accuracy = test_accuracy(model, testloader, label_hash_codes,device)
print(f'Test Accuracy: {accuracy}%')

/root/anaconda3/envs/deephashh/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/root/anaconda3/envs/deephashh/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet34_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet34_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Test Accuracy: 94.19%


In [73]:
import os

import train
train_loader,testloader = train.load_dataset('clean_label',0.0)
for iter ,(data, labels) in enumerate(train_loader):
    # 在这里，'data' 是数据（通常是图像），'labels' 是这批数据对应的标签
    if(iter==1):
        print("train")
        print(labels)  # 打印标签

for iter ,(data, labels) in enumerate(testloader):
    # 在这里，'data' 是数据（通常是图像），'labels' 是这批数据对应的标签
    if(iter==1):
        print("test")
        print(labels)  # 打印标签



train
tensor([3, 9, 9, 4, 7, 7, 2, 4, 2, 3, 0, 7, 6, 2, 4, 4, 4, 5, 7, 0, 6, 3, 6, 2,
        6, 6, 0, 1, 1, 7, 0, 2, 0, 0, 6, 8, 8, 1, 1, 9, 1, 4, 2, 8, 5, 2, 8, 5,
        2, 6, 4, 3, 5, 9, 4, 7, 3, 5, 9, 0, 2, 3, 7, 3, 8, 8, 9, 2, 5, 9, 1, 7,
        1, 8, 4, 0, 1, 9, 5, 5, 0, 4, 4, 0, 7, 8, 9, 7, 2, 9, 1, 5, 3, 2, 7, 1,
        3, 7, 2, 3, 2, 4, 8, 3, 8, 1, 7, 7, 4, 4, 6, 0, 5, 9, 2, 5, 9, 7, 6, 9,
        0, 2, 7, 6, 3, 1, 4, 3, 3, 1, 1, 7, 3, 1, 1, 8, 2, 3, 8, 1, 7, 5, 0, 9,
        4, 9, 5, 8, 4, 5, 7, 3, 2, 4, 0, 4, 5, 5, 6, 4, 8, 8, 3, 4, 0, 1, 7, 9,
        6, 7, 4, 5, 1, 3, 6, 2, 3, 5, 7, 7, 5, 9, 3, 2, 3, 9, 1, 4, 1, 8, 6, 7,
        7, 8, 3, 9, 7, 5, 2, 2, 4, 2, 2, 2, 4, 1, 0, 5, 8, 0, 9, 3, 4, 1, 0, 2,
        3, 2, 5, 8, 3, 3, 6, 6, 6, 9, 9, 3, 6, 2, 7, 5, 2, 4, 5, 7, 7, 0, 5, 3,
        3, 9, 6, 1, 0, 0, 3, 8, 4, 1, 5, 9, 6, 0, 6, 2])


KeyboardInterrupt: 

In [20]:
import algotrue
train_loader,testloader = algotrue.load_dataset('clean_label',64)
for iter ,(data, labels) in enumerate(train_loader):
    # 在这里，'data' 是数据（通常是图像），'labels' 是这批数据对应的标签
    if(iter==1):
        print("train")
        print(labels)  # 打印标签

for iter ,(data, labels) in enumerate(testloader):
    # 在这里，'data' 是数据（通常是图像），'labels' 是这批数据对应的标签
    if(iter==1):
        print("test")
        print(labels)  # 打印标签


Files already downloaded and verified
train
tensor([8, 0, 3, 3, 2, 3, 4, 2, 6, 8, 0, 1, 6, 3, 8, 0, 0, 1, 7, 2, 9, 7, 2, 7,
        3, 1, 4, 3, 0, 9, 3, 2, 5, 7, 9, 0, 6, 5, 4, 5, 0, 9, 2, 2, 7, 4, 5, 9,
        0, 3, 7, 9, 4, 3, 4, 3, 1, 6, 9, 1, 1, 0, 7, 9])
test
tensor([6, 2, 1, 2, 3, 7, 2, 6, 8, 8, 0, 2, 9, 3, 3, 8, 8, 1, 1, 7, 2, 5, 2, 7,
        8, 9, 0, 3, 8, 6, 4, 6, 6, 0, 0, 7, 4, 5, 6, 3, 1, 1, 3, 6, 8, 7, 4, 0,
        6, 2, 1, 3, 0, 4, 2, 7, 8, 3, 1, 2, 8, 0, 8, 3])


In [15]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from dataloader import dataloaders

device = torch.device("cuda")
hash_bits = 64 # 假设哈希编码的位数
model_name = "resnet34"
batch_size = 64
noise_rate=0.0

with open('./labels/64_cifar10_10_class.pkl', 'rb') as f:
    label_hash_codes= torch.load(f)
label_hash_codes.to(device)

# 1. 加载CIFAR-10数据集
transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
train_loader,testloader=dataloaders(root = './data',transform_train=transform,transform_test=transform,noise_type='clean_label')
for iter ,(data, labels) in enumerate(train_loader):
    # 在这里，'data' 是数据（通常是图像），'labels' 是这批数据对应的标签
    if(iter==1):
        print("train")
        print(labels)  # 打印标签

for iter ,(data, labels) in enumerate(testloader):
    # 在这里，'data' 是数据（通常是图像），'labels' 是这批数据对应的标签
    if(iter==1):
        print("test")
        print(labels)  # 打印标签


Files already downloaded and verified
Files already downloaded and verified
train
tensor([4, 5, 5, 4, 8, 7, 9, 1, 8, 8, 8, 1, 1, 4, 6, 8, 6, 7, 8, 0, 8, 9, 9, 0,
        4, 5, 3, 2, 6, 4, 0, 2, 5, 9, 2, 0, 2, 1, 1, 4, 9, 4, 6, 4, 8, 6, 3, 9,
        1, 7, 1, 3, 5, 4, 2, 8, 0, 4, 7, 0, 5, 1, 5, 7])
test
tensor([6, 2, 1, 2, 3, 7, 2, 6, 8, 8, 0, 2, 9, 3, 3, 8, 8, 1, 1, 7, 2, 5, 2, 7,
        8, 9, 0, 3, 8, 6, 4, 6, 6, 0, 0, 7, 4, 5, 6, 3, 1, 1, 3, 6, 8, 7, 4, 0,
        6, 2, 1, 3, 0, 4, 2, 7, 8, 3, 1, 2, 8, 0, 8, 3])


In [16]:
from utils.condition import cifar10ntrainloader
import torchvision
noise_type = 'clean_label'
batch_size=256
transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

trainloader = cifar10ntrainloader(noise_type,transform,batch_size)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=False, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size, shuffle=False, num_workers=30)
testloader.dataset

Files already downloaded and verified


Dataset CIFAR10
    Number of datapoints: 10000
    Root location: ./data
    Split: Test
    StandardTransform
Transform: Compose(
               Resize(size=256, interpolation=bilinear, max_size=None, antialias=True)
               CenterCrop(size=(224, 224))
               ToTensor()
               Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
           )

In [1]:
import torch

# 假设 a 和 b 是形状为 m x n 的两个矩阵
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])

# 先进行元素级乘法
elementwise_product = torch.mul(a, b)

# 然后对每一行求和，以得到每一行的点积结果
rowwise_dot_product = torch.sum(elementwise_product, dim=1)

print(rowwise_dot_product)


tensor([ 50, 167])
